menu:
  home: / || fa fa-home
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  about: /about/ || fa fa-user

local_search:
  enable: true

footer:
  beian:
    enable: true
    icp: 浙ICP备2021005492号-1




