name: build

on:
  push:
    branches-ignore: [ master ]
  workflow_dispatch:
  repository_dispatch:

jobs:
  Deploy-Hexo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout hexo framework
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build
        run: |
          npm install
          npx hexo generate

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: site_html
          path: ./public
