name: deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 0 * * *'
  workflow_call:
    secrets:
      KNOWLEDGE:
        required: true

jobs:
  Deploy-Hexo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout hexo framework
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build
        run: |
          npm install
          npx hexo generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
