name: Hexo

on:
  push:
    branches:
      - master  # Set a branch to deploy
      - 'feature/writer'  # Writer is allow to trigger deploy
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  Deploy-Hexo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.KNOWLEDGE }}
          submodules: recursive
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - run: git submodule update --remote

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0

      - name: Build
        run: |
          npm install
          npx hexo generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true

